version: '3.12'

services:
  psm-backend:
    # 构建当前目录下的 Dockerfile
    build: .
    # 容器名称
    container_name: psm_backend
    ports:
      - "3456:3456"
    # 卷挂载，用于数据持久化
    # 将主机当前目录下的 data 文件夹挂载到容器的 /app 目录
    # 将主机当前目录下的 uploads 文件夹挂载到容器的 /app/uploads 目录
    volumes:
      - ./psm.db:/app/psm.db
      - ./uploads:/app/uploads
    # 设置容器总是自动重启
    restart: unless-stopped
    # 设置环境变量 (如果您的应用需要)
    # environment:
    #   - FLASK_ENV=production
