"""补卡添加关联

Revision ID: 3d10375f8736
Revises: 5061e2f1f20a
Create Date: 2025-07-29 17:18:46.089859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '3d10375f8736'
down_revision = '5061e2f1f20a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_clockin_details', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('request_type', sa.Enum('LEAVE', 'CLOCK_IN', name='requesttypeenum'), nullable=False))

    # ### end Alembic commands ###


op.add_column('report_clockin_details', sa.Column('request_type', sa.Enum('LEAVE',
                                                                          'CLOCK_IN', name='requesttypeenum'),
                                                  nullable=True))

op.execute(text("UPDATE report_clockin_details SET request_type = 'CLOCK_IN' WHERE  request_type IS NULL"))

op.alter_column('report_clockin_details', 'request_type',
                existing_type=sa.Enum('LEAVE', 'CLOCK_IN', name='requesttypeenum'), nullable=False,
                existing_nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_clockin_details', schema=None) as batch_op:
        batch_op.drop_column('request_type')
    op.drop_column('report_clockin_details', 'request_type')
    # ### end Alembic commands ###
