"""为子项目成员添加多对多

Revision ID: 3d9f23947b50
Revises: 66bb2018562e
Create Date: 2025-07-08 16:05:35.935454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9f23947b50'
down_revision = '66bb2018562e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subproject_members',
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.id'], name=op.f('fk_subproject_members_subproject_id_subprojects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subproject_members_user_id_users')),
    sa.PrimaryKeyConstraint('subproject_id', 'user_id', name=op.f('pk_subproject_members'))
    )
    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subprojects_employee_id_users'), type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_subprojects_employee_id_users'), 'users', ['employee_id'], ['id'], ondelete='SET NULL')

    op.drop_table('subproject_members')
    # ### end Alembic commands ###
