""""Implement_session_tracking_and_remove_feedback_model"

Revision ID: 5061e2f1f20a
Revises: e3c28f3c364d
Create Date: 2025-07-25 17:12:12.946818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5061e2f1f20a'
down_revision = 'e3c28f3c364d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=50), nullable=True, comment="前端模块名，例如 'ai', 'project'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.drop_column('module')

    # ### end Alembic commands ###
