"""Add edit tracking to projects and tasks

Revision ID: b8bcee4198c8
Revises: 60aaa3119dd7
Create Date: 2025-08-11 10:13:00.921683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bcee4198c8'
down_revision = '60aaa3119dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_entity_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment="实体类型, e.g., 'project', 'task'"),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='实体ID'),
    sa.Column('duration_seconds', sa.Integer(), nullable=False, comment='本次编辑时长(秒)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_entity_activities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_entity_activities'))
    )
    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True, comment='编辑次数'))
        batch_op.add_column(sa.Column('total_edit_duration', sa.Integer(), nullable=True, comment='总编辑时长(秒)'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True, comment='编辑次数'))
        batch_op.add_column(sa.Column('total_edit_duration', sa.Integer(), nullable=True, comment='总编辑时长(秒)'))

    with op.batch_alter_table('stage_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True, comment='编辑次数'))
        batch_op.add_column(sa.Column('total_edit_duration', sa.Integer(), nullable=True, comment='总编辑时长(秒)'))

    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True, comment='编辑次数'))
        batch_op.add_column(sa.Column('total_edit_duration', sa.Integer(), nullable=True, comment='总编辑时长(秒)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subprojects', schema=None) as batch_op:
        batch_op.drop_column('total_edit_duration')
        batch_op.drop_column('edit_count')

    with op.batch_alter_table('stage_tasks', schema=None) as batch_op:
        batch_op.drop_column('total_edit_duration')
        batch_op.drop_column('edit_count')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('total_edit_duration')
        batch_op.drop_column('edit_count')

    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.drop_column('total_edit_duration')
        batch_op.drop_column('edit_count')

    op.drop_table('user_entity_activities')
    # ### end Alembic commands ###
