"""Add AI feature models and modifications

Revision ID: e3c28f3c364d
Revises: e69d4ed6fc3d
Create Date: 2025-07-24 16:46:09.085517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c28f3c364d'
down_revision = 'e69d4ed6fc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False, comment='配置项的键'),
    sa.Column('value', sa.String(length=255), nullable=True, comment='配置项的值'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_configs')),
    sa.UniqueConstraint('key', name=op.f('uq_system_configs_key'))
    )
    with op.batch_alter_table('ai_api', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ai_api_user_id'), ['user_id'])

    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), nullable=True))
        batch_op.drop_column('tokens_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')

    with op.batch_alter_table('ai_api', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ai_api_user_id'), type_='unique')

    op.drop_table('system_configs')
    # ### end Alembic commands ###
